project:
  type: website
  preview:
    port: 3000
  output-dir: docs

website:
  title: "conjugate.dev"
  search: false
  navbar:
    title: "Conjugate"
    logo: static/img/conjugate.png
    right:
      - icon: github
        href: github.com/bgautijonsson/conjugate
  sidebar:
    - id: id-dplyr
      title: dplyr
      contents: 
        - ./courses/dplyr/index.qmd
        - ./courses/dplyr/chapter1/index.qmd
        - ./courses/dplyr/chapter2/index.qmd
        - ./courses/dplyr/chapter3/index.qmd

format:
  live-html:
    theme: [flatly, theme.scss]
    css: styles.css
engine: knitr