project:
  type: website
  preview:
    port: 3000

website:
  title: "conjugate.dev"
  search: false
  navbar:
    title: "conjugate.dev"
    right:
      - icon: github
        href: github.com

format:
  html:
    theme: [flatly, theme.scss]
    css: styles.css


engine: knitr